spring.application.name=credit-card-service
server.port=8085
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_card_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Enable Virtual Threads
spring.threads.virtual.enabled=true

# Credit Card Configuration
credit-card.default.credit-limit=50000
credit-card.default.interest-rate=36.0
credit-card.default.annual-fee=499
credit-card.default.billing-cycle-day=1
