spring.application.name=customer-service
server.port=8080
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/bank_system
spring.datasource.username=postgres
spring.datasource.password=root
# below line is important
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# why because flyway and hibernate act differently
spring.jpa.properties.hibernate.default_schema=customer_db


#: Enable Virtual Threads
spring.threads.virtual.enabled=true


# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration

# database schema name
spring.flyway.schemas=customer_db

# if schema does not exist, Flyway can create it
spring.flyway.create-schemas=true