spring.application.name=account-service
server.port=8081
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/account_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

#: Enable Virtual Threads
spring.threads.virtual.enabled=true

# kafka configuration
#why we added below ?
# cause kafka only support string serializer, but we are sending Object
# kafka cannot send object directly
# Solution convert Object --> JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer