spring.application.name=loan-service
server.port=8084
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/bank_system
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

#: Enable Virtual Threads
spring.threads.virtual.enabled=true

# Loan Configuration
loan.default.interest-rate=12.5

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration

# database schema name
spring.flyway.schemas=loan_db

# if schema does not exist, Flyway can create it
spring.flyway.create-schemas=true

# why because flyway and hibernate act differently
spring.jpa.properties.hibernate.default_schema=loan_db